import { Figtree } from "next/font/google";
import "./globals.css";
import PromotionBar from "./components/PromotionBar";
import Header from "./components/layout/Header";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});

export const metadata = {
  title: "Netzet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en" className={figtree.variable}>
      <body className="flex flex-col min-h-screen font-figtree">
        <PromotionBar />
        <Header />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
