import { Urbanist } from "next/font/google";
import "./globals.css";
import PromotionBar from "./components/PromotionBar";
import Header from "./components/layout/Header";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
});

export const metadata = {
  title: "Netzet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={urbanist.variable}>
      <body className="flex flex-col min-h-screen font-urbanist">
        <PromotionBar />
        <Header />
        <div className="flex justify-center">
          <main className="flex-grow max-w-[1536px] relative">{children}</main>
        </div>
      </body>
    </html>
  );
}
